const LexEditorTheme = {
  characterLimit: "LexEditorTheme__characterLimit",
  code: "LexEditorTheme__code",
  codeHighlight: {
    atrule: "token_atrule",
    attr: "token_attr-name",
    boolean: "token_boolean",
    builtin: "token_builtin",
    cdata: "token_cdata",
    char: "token_char",
    class: "token_class",
    "class-name": "token_class-name",
    comment: "token_comment",
    constant: "token_constant",
    control: "token_control",
    deleted: "token_deleted",
    directive: "token_directive",
    doctype: "token_doctype",
    entity: "token_entity",
    function: "token_function",
    "function-variable": "token_function-variable",
    "generic-function": "token_generic-function",
    generic: "token_generic",
    important: "token_important",
    inserted: "token_inserted",
    keyword: "token_keyword",
    namespace: "token_namespace",
    number: "token_number",
    operator: "token_operator",
    parameter: "token_parameter",
    placeholder: "token_placeholder",
    prolog: "token_prolog",
    property: "token_property",
    punctuation: "token_punctuation",
    regex: "token_regex",
    selector: "token_selector",
    statement: "token_statement",
    string: "token_string",
    symbol: "token_symbol",
    tag: "token_tag",
    url: "token_url",
    unit: "token_unit",
    variable: "token_variable",
  },
  hashtag: "LexEditorTheme__hashtag",
  heading: {
    h1: "LexEditorTheme__h1 text-6xl",
    h2: "LexEditorTheme__h2 text-5xl",
    h3: "LexEditorTheme__h3 text-4xl",
    h4: "LexEditorTheme__h4 text-3xl",
    h5: "LexEditorTheme__h5 text-2xl",
  },
  image: "editor-image",
  link: "LexEditorTheme__link",
  list: {
    listitem: "LexEditorTheme__listItem",
    nested: {
      listitem: "LexEditorTheme__nestedListItem",
    },
    olDepth: [
      "LexEditorTheme__ol1",
      "LexEditorTheme__ol2",
      "LexEditorTheme__ol3",
      "LexEditorTheme__ol4",
      "LexEditorTheme__ol5",
    ],
    ul: "LexEditorTheme__ul max-w-md space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400",
  },
  ltr: "LexEditorTheme__ltr",
  paragraph: "LexEditorTheme__paragraph",
  quote: "LexEditorTheme__quote text-xl italic font-semibold text-gray-300 ",
  rtl: "LexEditorTheme__rtl",
  table: "LexEditorTheme__table",
  tableCell: "LexEditorTheme__tableCell",
  tableCellHeader: "LexEditorTheme__tableCellHeader",
  text: {
    bold: "LexEditorTheme__textBold text-white",
    code: "LexEditorTheme__textCode",
    italic: "LexEditorTheme__textItalic",
    strikethrough: "LexEditorTheme__textStrikethrough line-through",
    underline: "LexEditorTheme__textUnderline underline underline-offset-4",
    underlineStrikethrough:
      "LexEditorTheme__textUnderlineStrikethrough [text-decoration:underline_line-through]",
  },
}

export default LexEditorTheme
